name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup packages
        uses: ./.github/actions/setup

  format:
    name: Run biome check
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup packages
        uses: ./.github/actions/setup
      - name: Biome check
        run: npm run check

  test:
    name: Run test
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup packages
        uses: ./.github/actions/setup
      - name: Vitest tests
        run: npm run test

  typecheck:
    name: Run typecheck
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup packages
        uses: ./.github/actions/setup
      - name: check types
        run: npm run typecheck
